quarkus.rest-client."org.opencodespace.wordle.client.discord.api.UserApiClient".url=http://localhost:8080
quarkus.rest-client."org.opencodespace.wordle.client.discord.api.GuessApiClient".url=http://localhost:8080
quarkus.rest-client."org.opencodespace.wordle.client.discord.api.WordleApiClient".url=https://www.nytimes.com/svc/wordle/v2
quarkus.http.port=8081